//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPBD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRATNEEntities : DbContext
    {
        public PRATNEEntities()
            : base("name=PRATNEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Expediente> Expediente { get; set; }
        public virtual DbSet<Expediente_Compuesto_por> Expediente_Compuesto_por { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Paciente_Tiene> Paciente_Tiene { get; set; }
        public virtual DbSet<SolicitudAtencion> SolicitudAtencion { get; set; }
        public virtual DbSet<Terapeuta> Terapeuta { get; set; }
        public virtual DbSet<Terapeuta_Atiende> Terapeuta_Atiende { get; set; }
        public virtual DbSet<Terapeuta_Realiza> Terapeuta_Realiza { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
