//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAtencion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudAtencion()
        {
            this.Expediente_Compuesto_por = new HashSet<Expediente_Compuesto_por>();
        }
    
        public int Id_SolicitudAtencion { get; set; }
        public string PerVive { get; set; }
        public string MotivoConsulta { get; set; }
        public string HistoriaCaso { get; set; }
        public string PruebasAplicadas { get; set; }
        public string Nombre_EstudianteApoyo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente_Compuesto_por> Expediente_Compuesto_por { get; set; }
    }
}
