//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terapeuta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terapeuta()
        {
            this.Terapeuta_Realiza = new HashSet<Terapeuta_Realiza>();
            this.Terapeuta_Atiende = new HashSet<Terapeuta_Atiende>();
        }
    
        public int Id_Terapeuta { get; set; }
        public string Organizacion { get; set; }
        public string Matricula { get; set; }
        public string Universidad { get; set; }
        public string Grado { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string Escolaridad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terapeuta_Realiza> Terapeuta_Realiza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terapeuta_Atiende> Terapeuta_Atiende { get; set; }
    }
}
